doctrine_mongodb:
  connections:
    default:
      server: '%env(resolve:MONGODB_URL)%'
      options: {}

  default_database: iwis

  document_managers:
    default:
      auto_mapping: true
      mappings:
        Document:
          is_bundle: false
          type: attribute
          dir: '%kernel.project_dir%/src/Domain/Entity/Document'
          prefix: 'App\Domain\Entity\Document'
          alias: Document