# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\UI\:
        resource: '../src/UI/'
        tags: ['controller.service_arguments']

    App\Application\CommandHandler\:
        resource: '../src/Application/CommandHandler/'
        tags: ['messenger.message_handler']

    App\Infrastructure\:
        resource: '../src/Infrastructure/'

    App\Domain\Repository\ProductRepositoryInterface: '@App\Infrastructure\Persistence\Mongo\MongoProductRepository'
    App\Domain\Repository\Relational\ProductRepositoryInterface: '@App\Infrastructure\Persistence\Sql\ProductDoctrineRepository'
    App\Domain\Repository\Relational\CategoryRepositoryInterface: '@App\Infrastructure\Persistence\Sql\CategoryDoctrineRepository'

    App\Application\DTO\:
        resource: '../src/Application/DTO/'
        public: false

    App\Domain\:
        resource: '../src/Domain/'
        exclude:
            - '../src/Domain/**/*Handler.php'
            - '../src/Domain/**/*Repository.php'
            - '../src/Domain/**/*Event.php'

    App\Infrastructure\Persistence\Mongo\BufferedMongoFlusher:
        arguments:
            $dm: '@doctrine_mongodb.odm.document_manager'