version: '3.8'

services:
  php:
    build: ./docker/php
    container_name: iwis_php
    volumes:
      - ../project:/var/www
    depends_on:
      - mysql
      - mongodb
      - rabbitmq
    environment:
      PHP_IDE_CONFIG: "serverName=iwis"

  nginx:
    image: nginx:stable-alpine
    container_name: iwis_nginx
    ports:
      - "8080:80"
    volumes:
      - ../project/public:/var/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: iwis_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iwis
      MYSQL_USER: iwis
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - iwis_mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:6.0
    container_name: iwis_mongo
    ports:
      - "27017:27017"
    volumes:
      - iwis_mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: iwis_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  iwis_mysql_data:
  iwis_mongo_data: